package slack

import (
	"time"

	"github.com/fiam/toolmux/internal/actions"
	"github.com/fiam/toolmux/internal/providers"
	"github.com/fiam/toolmux/internal/providers/slack/slackapi"
	"github.com/fiam/toolmux/internal/slackauth"
)

const (
	providerID       = "slack"
	authTypeDirect   = "token_cookie"
	authTypeUser     = "oauth_user"
	authTypeBroker   = "oauth_broker"
	callbackPath     = "/oauth/slack/callback"
	oauthRefreshSkew = time.Minute
)

var defaultOAuthScopes = []string{
	"channels:read",
	"groups:read",
	"im:read",
	"mpim:read",
	"im:write",
	"channels:history",
	"groups:history",
	"im:history",
	"mpim:history",
	"chat:write",
	"reactions:write",
	"files:read",
	"users:read",
	"usergroups:read",
	"usergroups:write",
	"search:read",
}

var slackAuthExtract = slackauth.Extract

func init() {
	providers.Register(Descriptor())
}

func Descriptor() providers.Provider {
	return providers.Provider{
		ID:             providerID,
		DisplayName:    "Slack",
		AuthMode:       "token_cookie_or_oauth",
		BaseURLEnv:     "TOOLMUX_SLACK_API_URL",
		DefaultBaseURL: slackapi.DefaultAPIBaseURL,
		Tree: actions.Group("slack",
			actions.Short("Use Slack"),
			actions.Children(
				slackTool("auth_test", "Show Slack auth identity", "connection", actions.VerbRead, actions.EffectRead),
				slackTool("conversations_history", "Get Slack conversation history", "message", actions.VerbRead, actions.EffectRead,
					actions.StringFlag("channel_id", "", "Slack channel, DM, or MPIM ID"),
					actions.BoolFlag("include_activity_messages", false, "include join, leave, and other activity messages"),
					actions.StringFlag("cursor", "", "Slack pagination cursor"),
					actions.StringFlag("oldest", "", "only include messages after this Slack timestamp"),
					actions.StringFlag("latest", "", "only include messages before this Slack timestamp"),
					actions.BoolFlag("inclusive", false, "include messages matching oldest or latest timestamps"),
					actions.StringFlag("limit", "100", "maximum messages to fetch"),
				),
				slackTool("conversations_replies", "Get Slack thread replies", "message", actions.VerbRead, actions.EffectRead,
					actions.StringFlag("channel_id", "", "Slack channel, DM, or MPIM ID"),
					actions.StringFlag("thread_ts", "", "Slack thread timestamp"),
					actions.BoolFlag("include_activity_messages", false, "include join, leave, and other activity messages"),
					actions.StringFlag("cursor", "", "Slack pagination cursor"),
					actions.StringFlag("oldest", "", "only include replies after this Slack timestamp"),
					actions.StringFlag("latest", "", "only include replies before this Slack timestamp"),
					actions.BoolFlag("inclusive", false, "include replies matching oldest or latest timestamps"),
					actions.StringFlag("limit", "100", "maximum replies to fetch"),
				),
				slackTool("conversations_add_message", "Send a Slack message", "message", actions.VerbSend, actions.EffectWrite,
					actions.StringFlag("channel_id", "", "Slack channel, DM, or MPIM ID"),
					actions.StringFlag("thread_ts", "", "Slack thread timestamp"),
					actions.StringFlag("text", "", "message text"),
					actions.StringFlag("payload", "", "message payload; accepted as an alias for text"),
					actions.StringFlag("content_type", "text/markdown", "message content type"),
					actions.BoolFlag("dry-run", false, "show the Slack request without sending it"),
				),
				slackTool("conversations_open", "Open a Slack DM or MPIM conversation", "conversation", actions.VerbOpen, actions.EffectWrite,
					actions.StringFlag("user_id", "", "single Slack user ID to open a DM with"),
					actions.StringFlag("users", "", "comma-separated Slack user IDs to open a DM or MPIM with"),
					actions.BoolFlag("prevent_creation", false, "do not create a new conversation"),
					actions.BoolFlag("return_im", true, "return the full IM conversation"),
					actions.BoolFlag("dry-run", false, "show the Slack request without opening a conversation"),
				),
				slackTool("reactions_add", "Add a Slack reaction", "reaction", actions.VerbCreate, actions.EffectWrite,
					actions.StringFlag("channel_id", "", "Slack channel, DM, or MPIM ID"),
					actions.StringFlag("timestamp", "", "message timestamp"),
					actions.StringFlag("emoji", "", "emoji name without colons"),
					actions.BoolFlag("dry-run", false, "show the Slack request without sending it"),
				),
				slackTool("reactions_remove", "Remove a Slack reaction", "reaction", actions.VerbDelete, actions.EffectWrite,
					actions.StringFlag("channel_id", "", "Slack channel, DM, or MPIM ID"),
					actions.StringFlag("timestamp", "", "message timestamp"),
					actions.StringFlag("emoji", "", "emoji name without colons"),
					actions.BoolFlag("dry-run", false, "show the Slack request without sending it"),
				),
				slackTool("attachment_get_data", "Download Slack attachment data", "attachment", actions.VerbRead, actions.EffectRead,
					actions.StringFlag("file_id", "", "Slack file ID"),
				),
				slackTool("conversations_search_messages", "Search Slack messages", "message", actions.VerbSearch, actions.EffectRead,
					actions.StringFlag("search_query", "", "Slack search query"),
					actions.StringFlag("filter_in_channel", "", "channel filter"),
					actions.StringFlag("filter_in_im_or_mpim", "", "DM or MPIM filter"),
					actions.StringFlag("filter_users_with", "", "with-user filter"),
					actions.StringFlag("filter_users_from", "", "from-user filter"),
					actions.StringFlag("filter_date_before", "", "before date filter"),
					actions.StringFlag("filter_date_after", "", "after date filter"),
					actions.StringFlag("filter_date_on", "", "on date filter"),
					actions.StringFlag("filter_date_during", "", "during date filter"),
					actions.BoolFlag("filter_threads_only", false, "search only thread messages"),
					actions.StringFlag("cursor", "", "Slack pagination cursor"),
					actions.IntFlag("limit", 20, "maximum matches to return"),
				),
				slackTool("conversations_unreads", "List unread Slack conversations", "message", actions.VerbRead, actions.EffectRead,
					actions.BoolFlag("include_messages", true, "include unread or recent messages"),
					actions.StringFlag("channel_types", "all", "channel type filter: all, dm, group_dm, partner, internal"),
					actions.IntFlag("max_channels", 50, "maximum channels to inspect"),
					actions.IntFlag("max_messages_per_channel", 10, "maximum messages per channel"),
					actions.BoolFlag("mentions_only", false, "only include channels with mentions when Slack exposes that count"),
					actions.BoolFlag("include_muted", false, "include muted channels"),
				),
				slackTool("conversations_mark", "Mark a Slack conversation read", "message", actions.VerbUpdate, actions.EffectWrite,
					actions.StringFlag("channel_id", "", "Slack channel, DM, or MPIM ID"),
					actions.StringFlag("ts", "", "message timestamp to mark through"),
					actions.BoolFlag("dry-run", false, "show the Slack request without sending it"),
				),
				slackTool("channels_list", "List Slack channels", "conversation", actions.VerbList, actions.EffectRead,
					actions.StringFlag("channel_types", "public_channel,private_channel,mpim,im", "comma-separated Slack channel types"),
					actions.StringFlag("sort", "", "sort mode, for example popularity"),
					actions.IntFlag("limit", 100, "maximum channels to return"),
					actions.StringFlag("cursor", "", "Slack pagination cursor"),
				),
				slackTool("users_conversations", "List conversations the Slack user is a member of", "conversation", actions.VerbList, actions.EffectRead,
					actions.StringFlag("user_id", "", "Slack user ID whose shared conversations should be listed; defaults to the authenticated user"),
					actions.StringFlag("team_id", "", "Slack workspace team ID for org-level tokens"),
					actions.StringFlag("channel_types", "public_channel,private_channel,mpim,im", "comma-separated Slack conversation types"),
					actions.BoolFlag("exclude_archived", true, "exclude archived conversations"),
					actions.StringFlag("sort", "", "sort mode, for example popularity"),
					actions.IntFlag("limit", 100, "maximum conversations to return"),
					actions.StringFlag("cursor", "", "Slack pagination cursor"),
				),
				slackTool("experimental_conversations_list", "Experimentally list Slack web-session conversations", "conversation", actions.VerbList, actions.EffectRead,
					actions.StringFlag("query", "", "case-insensitive local filter for conversation name, ID, or user ID"),
					actions.BoolFlag("include_ims", false, "include direct messages returned by Slack web-session bootstrap"),
					actions.BoolFlag("include_mpims", false, "include multi-person direct messages returned by Slack web-session bootstrap"),
					actions.BoolFlag("exclude_archived", true, "exclude archived conversations"),
					actions.IntFlag("limit", 100, "maximum conversations to return after filtering; 0 returns all"),
				),
				slackTool("usergroups_list", "List Slack user groups", "usergroup", actions.VerbList, actions.EffectRead,
					actions.BoolFlag("include_users", false, "include user IDs in each group"),
					actions.BoolFlag("include_count", true, "include user counts"),
					actions.BoolFlag("include_disabled", false, "include disabled user groups"),
				),
				slackTool("usergroups_me", "Manage your Slack user group membership", "usergroup", actions.VerbUpdate, actions.EffectWrite,
					actions.StringFlag("action", "", "action to perform: list, join, or leave"),
					actions.StringFlag("usergroup_id", "", "Slack user group ID for join or leave"),
					actions.BoolFlag("dry-run", false, "show the Slack request without sending it"),
				),
				slackTool("usergroups_create", "Create a Slack user group", "usergroup", actions.VerbCreate, actions.EffectWrite,
					actions.StringFlag("name", "", "user group display name"),
					actions.StringFlag("handle", "", "mention handle without @"),
					actions.StringFlag("description", "", "user group description"),
					actions.StringFlag("channels", "", "comma-separated default channel IDs"),
					actions.BoolFlag("dry-run", false, "show the Slack request without sending it"),
				),
				slackTool("usergroups_update", "Update a Slack user group", "usergroup", actions.VerbUpdate, actions.EffectWrite,
					actions.StringFlag("usergroup_id", "", "Slack user group ID"),
					actions.StringFlag("name", "", "new display name"),
					actions.StringFlag("handle", "", "new mention handle without @"),
					actions.StringFlag("description", "", "new description"),
					actions.StringFlag("channels", "", "comma-separated default channel IDs"),
					actions.BoolFlag("dry-run", false, "show the Slack request without sending it"),
				),
				slackTool("usergroups_users_update", "Replace Slack user group members", "usergroup", actions.VerbUpdate, actions.EffectWrite,
					actions.StringFlag("usergroup_id", "", "Slack user group ID"),
					actions.StringFlag("users", "", "comma-separated Slack user IDs"),
					actions.BoolFlag("dry-run", false, "show the Slack request without sending it"),
				),
				slackTool("users_search", "Search Slack users", "user", actions.VerbSearch, actions.EffectRead,
					actions.StringFlag("query", "", "user search query"),
					actions.IntFlag("limit", 10, "maximum users to return"),
				),
			),
		),
		Handlers: map[string]actions.Handler{
			"slack.auth_test":                       handleAuthTest,
			"slack.conversations_history":           handleConversationsHistory,
			"slack.conversations_replies":           handleConversationsReplies,
			"slack.conversations_add_message":       handleConversationsAddMessage,
			"slack.conversations_open":              handleConversationsOpen,
			"slack.reactions_add":                   handleReactionsAdd,
			"slack.reactions_remove":                handleReactionsRemove,
			"slack.attachment_get_data":             handleAttachmentGetData,
			"slack.conversations_search_messages":   handleConversationsSearchMessages,
			"slack.conversations_unreads":           handleConversationsUnreads,
			"slack.conversations_mark":              handleConversationsMark,
			"slack.channels_list":                   handleChannelsList,
			"slack.users_conversations":             handleUsersConversations,
			"slack.experimental_conversations_list": handleExperimentalConversationsList,
			"slack.usergroups_list":                 handleUsergroupsList,
			"slack.usergroups_me":                   handleUsergroupsMe,
			"slack.usergroups_create":               handleUsergroupsCreate,
			"slack.usergroups_update":               handleUsergroupsUpdate,
			"slack.usergroups_users_update":         handleUsergroupsUsersUpdate,
			"slack.users_search":                    handleUsersSearch,
		},
		AddHandler:    handleAdd,
		RemoveHandler: handleRemove,
	}
}

func slackTool(name, short, resource string, verb actions.Verb, remote actions.Effect, opts ...actions.Option) actions.Spec {
	base := []actions.Option{
		actions.Short(short),
		actions.Description(slackToolDescription(name, short)),
		actions.RBAC(actions.ResourceName(resource), verb, remote),
	}
	base = append(base, opts...)
	return actions.Command(actions.LocalName(name), name, base...)
}

func slackToolDescription(name, fallback string) string {
	descriptions := map[string]string{
		"auth_test":                       "Validate the stored Slack credentials and return the authenticated team, user, team ID, user ID, and workspace URL. Use this first when Slack tools fail to distinguish bad auth from workspace or method restrictions.",
		"conversations_history":           "Read recent messages from a Slack channel, private channel, DM, or MPIM by conversation ID. Use --channel_id with IDs such as C123, G123, or D123. Slack timestamps are strings like 1712345678.000100; use --oldest, --latest, and --inclusive to page by time, and --cursor for Slack cursor pagination.",
		"conversations_replies":           "Read replies in a Slack thread. Pass --channel_id for the parent conversation and --thread_ts for the thread root timestamp, for example 1712345678.000100. Use this after search or history returns a message with replies.",
		"conversations_add_message":       "Send a Slack message to a channel, DM, or MPIM. Pass --channel_id and --text, or --payload as an alias for text. Use --thread_ts to reply in a thread. Use --dry-run to preview the request without sending.",
		"conversations_open":              "Open or resume a direct message or multi-person direct message. Pass --user_id for one user or --users with comma-separated Slack user IDs. Set --prevent_creation to avoid creating a new DM/MPIM when one does not already exist.",
		"reactions_add":                   "Add an emoji reaction to a Slack message. Pass --channel_id, --timestamp with the message ts, and --emoji without surrounding colons, for example white_check_mark. Use --dry-run to inspect the request.",
		"reactions_remove":                "Remove an emoji reaction from a Slack message. Pass --channel_id, --timestamp with the message ts, and --emoji without surrounding colons. Use --dry-run to inspect the request.",
		"attachment_get_data":             "Download a Slack file attachment by file ID. Text-like files return inline text content; binary files return base64 content. Slack file access still follows the authenticated user's permissions.",
		"conversations_search_messages":   "Search Slack messages visible to the authenticated user. Provide --search_query using Slack search syntax, or combine filters such as --filter_in_channel, --filter_users_from, --filter_date_after, and --filter_threads_only. This often works in Enterprise workspaces even when workspace-wide channel listing is restricted.",
		"conversations_unreads":           "List unread or recent Slack conversations and optionally include recent messages from each. This uses conversation listing plus history reads, so it may be restricted in Enterprise/Grid workspaces where conversations.list is disabled.",
		"conversations_mark":              "Mark a Slack conversation read through a timestamp. Pass --channel_id and optionally --ts; when --ts is omitted Toolmux uses the current time. Use --dry-run to inspect the request.",
		"channels_list":                   "List channel-like conversations in the workspace using Slack conversations.list. This is workspace-wide and may be blocked by Enterprise/Grid policy with enterprise_is_restricted. For channels the authenticated user is a member of, prefer users_conversations.",
		"users_conversations":             "List conversations the authenticated Slack user is a member of using Slack users.conversations. Try this for membership-focused channel discovery before workspace-wide channels_list. Some Enterprise/Grid workspaces may still restrict this public Web API method. Use --user_id only to narrow to conversations shared with another user; use --team_id when Slack requires an explicit workspace team ID for an org-level token.",
		"experimental_conversations_list": "Experimental: list Slack web-session conversations from Slack's web app bootstrap response. This uses an undocumented read-only web-session endpoint and is intended for Enterprise/Grid workspaces where documented public listing APIs return enterprise_is_restricted. Prefer documented tools when they work.",
		"usergroups_list":                 "List Slack user groups. Use --include_count for member counts, --include_users for member IDs, and --include_disabled when disabled user groups should be returned.",
		"usergroups_me":                   "Manage the authenticated user's membership in a Slack user group. Set --action to list, join, or leave. Join and leave require --usergroup_id. Use --dry-run to preview write operations.",
		"usergroups_create":               "Create a Slack user group. Pass --name and --handle, with optional --description and comma-separated default --channels. Use --dry-run to preview the request without creating anything.",
		"usergroups_update":               "Update a Slack user group. Pass --usergroup_id and any fields to change: --name, --handle, --description, or comma-separated default --channels. Use --dry-run to preview the request.",
		"usergroups_users_update":         "Replace the full member list of a Slack user group. Pass --usergroup_id and comma-separated --users. This is a replacement operation, not an append. Use --dry-run to preview the request.",
		"users_search":                    "Search Slack users by name, display name, real name, title, or email-like text visible to the authenticated user. Use --limit to bound the number of returned users.",
	}
	return firstNonEmpty(descriptions[name], fallback)
}
